### ISSUE TITLE
not downloadable "l1" product

### ISSUE THREAD

**Issue by researcher1212** [USGS-EROS/espa-api#102]
Good day!

Using Api for downloading "l1" products:
endpoint: https://espa.cr.usgs.gov/api/v0/order 
with data like: {"format":"gtiff","olitirs8_collection":{"inputs":["LC08_L1TP_179026_20170904_20170916_01_T1"],"products":["l1"]}}".

Until recently was fine.

But now, I getting 400 error with message: "order includes only Landsat Level-1 data products, please contact User Services for other available options"

What should I do for get just "l1" product?

**Comment by jakebrinkmann** [comment]
Hi there, 
The ESPA system uses Landsat Level-1 data as inputs for on-demand Level-2/Level-3 data processing. Optionally, the L1 input products can also be packaged along with the corresponding L2/L3 output products (TOA, BT, SR, PixelQA).

The Level-1 source data is already available for immediate download directly from other primary sources, such as EarthExplorer (https://earthexplorer.usgs.gov).   

* [Landsat Data Access](https://landsat.usgs.gov/landsat-data-access)
* [EarthExplorer Bulk Inventory Service](https://earthexplorer.usgs.gov/inventory/documentation/json-api)
* [Request `"bulk download access"` here](https://landsat.usgs.gov/contact)

**Comment by researcher1212** [comment]
Thank's!
