### ISSUE TITLE
Analysis Ready data?

### ISSUE THREAD

**Issue by rbavery** [USGS-EROS/espa-api#132]
Is there a way to programmatically query and download analysis ready data products?

**Comment by danzelenak-usgs** [comment]
We do not provide ARD products via ESPA.

Here is a list of our current data access portals.
https://www.usgs.gov/land-resources/nli/landsat/landsat-data-access?qt-science_support_page_related_con=0#qt-science_support_page_related_con

The EarthExplorer API link is where you'll want to get started, note that you'll need an EROS Registration System account to view that page (https://ers.cr.usgs.gov/register).
