### ISSUE TITLE
"Could not parse the request into json, status: 400"

### ISSUE THREAD

**Issue by athanasis** [USGS-EROS/espa-api#42]
Hi,

![espa_error](https://cloud.githubusercontent.com/assets/9377464/20678264/ba8a4610-b59e-11e6-889f-8f5d1e95c520.PNG)
When sending a POST request to the API with Git Shell I get the following rsponse
{
  "msg": "Could not parse the request into json",
  "status": 400
}

See the screen capture for details
I am using the same command as the one in the espa-api web page, i.e:

curl --user username:password -d '{"olitirs8": {
                                                    "inputs": ["LC80270292015233LGN00"], 
                                                    "products": ["sr"]
                                                 }, 
                                     "format": "gtiff", 
                                     "resize": {
                                                "pixel_size": 60, 
                                                "pixel_size_units": "meters"
                                                }, 
                                     "resampling_method": "nn", 
                                     "plot_statistics": true, 
                                     "projection": {
                                                    "aea": {
                                                            "standard_parallel_1": 29.5,
                                                            "standard_parallel_2": 45.5,
                                                            "central_meridian": -96.0,
                                                            "latitude_of_origin": 23.0,
                                                            "false_easting": 0.0,
                                                            "false_northing": 0.0,
                                                            "datum": "wgs84"
                                                            }
                                                    },
                                     "image_extents": {
                                                        "north": 0.0002695,
                                                        "south": 0,
                                                        "east": 0.0002695,
                                                        "west": 0,
                                                        "units": "dd"
                                                    },
                                     "note": "this is going to be sweet..."
                                     }' https://espa.cr.usgs.gov/api/v0/order

What is the appropriate way to use the API for a POST request?

Thank you.

**Comment by caustin-usgs** [comment]
hello @athanasis , if you copy+pasted directly from the docs on github, you'll have picked up a bunch of undesired encoded characters (new lines), those dont conform to the json standard.

**Comment by athanasis** [comment]
Hello Clay,
Thank you for your answer. I carefully inserted the json fragment in a text editor, removed very carefully all new line characters and fired the command. I also tried to run the POST from a locally stored json file by running the following command:
curl --user athanasis:[password_here] -XPOST -H 'Content-Type:application/json' -H 'Accept: application/json'  -d jsonfile2.json  https://espa.cr.usgs.gov/api/v0/order

However, it did not work (same error appeared, i.e. 'Could not parse the request into json'). 
Any suggestions, please?

Thank you.

**Comment by caustin-usgs** [comment]
I dont typically work from MS, but the following just worked for me:

curl --user username:xxxxxx -XPOST -H 'Content-Type:application/json' -H 'Accept: application/json' -d '{"olitirs8": {"inputs": ["LC80270292015233LGN00"],"products": ["sr"]},"format": "gtiff","resize": {"pixel_size": 60,"pixel_size_units": "meters"},"resampling_method": "nn","plot_statistics": true,"projection": {"aea": {"standard_parallel_1": 29.5,"standard_parallel_2": 45.5,"central_meridian": -96.0,"latitude_of_origin": 23.0,"false_easting": 0.0,"false_northing": 0.0,"datum": "wgs84"}},"note": "this is going to be sweet"}' https://espa.cr.usgs.gov/api/v1/order


on my linux machine, I got away with: 
curl --user $username:$pword -d '{"olitirs8": {"inputs": ["LC80270292015233LGN00"],"products": ["sr"]},"format": "gtiff","resize": {"pixel_size": 60,"pixel_size_units": "me    ters"},"resampling_method": "nn","plot_statistics": true,"projection": {"aea": {"standard_parallel_1": 29.5,"standard_parallel_2": 45.5,"central_meridian": -96.0,"latitude_    of_origin": 23.0,"false_easting": 0.0,"false_northing": 0.0,"datum": "wgs84"}},"note": "this is going to be sweet"}' https://espa.cr.usgs.gov/api/v1/order

**Comment by caustin-usgs** [comment]
if you're still having problems, the python requests library makes POST and GET requests pretty easy for example:

>>> import requests
>>> data = {"olitirs8": {"inputs": ["LC80270292015233LGN00"],"products": ["sr"]}
,"format": "gtiff","resize": {"pixel_size": 60,"pixel_size_units": "meters"},"re
sampling_method": "nn","plot_statistics": True,"projection": {"aea": {"standard_
parallel_1": 29.5,"standard_parallel_2": 45.5,"central_meridian": -96.0,"latitud
e_of_origin": 23.0,"false_easting": 0.0,"false_northing": 0.0,"datum": "wgs84"}}
,"note": "this is going to be sweet"}
>>>
>>> response = requests.post('https://espa.cr.usgs.gov/api/v1/order', json=data,
 auth=('xxxx','xxxx'))
>>> response.json()
{'orderid': 'clay.austin.ctr@usgs.gov-11282016-150058-453', 'status': 200}
>>>
>>>
>>>

**Comment by athanasis** [comment]
Unfortunatelly, I still cannot run it. I simply copy/paste the command you send me, specify my username/password, run it and  the following error appears (see screen capture)
![espa_error2](https://cloud.githubusercontent.com/assets/9377464/20686800/bdaa170c-b5c2-11e6-95f7-a060fa4e4a81.png)

Maybe there is something wrong with my PC settings, I will try it in another machine with english OS installed (mine is not English/american).

If I don't find it, I will try the python request. Should I work with the [espa-api-client 1.0.0.dev7](https://pypi.python.org/pypi/espa-api-client) library?

Thank you.

**Comment by stevefoga** [comment]
Hi @athanasis,

I'm using an English version of Windows, and still have similar issues when reproducing your issue. Try using the example POST request from the espa-api docs with **cmd.exe** instead of Windows PowerShell before resorting to additional tools.

**Comment by athanasis** [comment]
Hi,
Even with cmd.exe similar errors appear:

>C:\Users\User\Documents\curl-7.51.0\src\curl --user athanasis:XXXXX -XPOST -H 'Content-Type:application/json' -H ' Accept: application/json' -d '{"olitirs8": {"inputs": ["LC80270292015233LGN00"],
"products": ["sr"]},"format": "gtiff","resize": {"pixel_size": 60,"pixel_size_un
its": "meters"},"resampling_method": "nn","plot_statistics": true,"projection":
{"aea": {"standard_parallel_1": 29.5,"standard_parallel_2": 45.5,"central_meridi
an": -96.0,"latitude_of_origin": 23.0,"false_easting": 0.0,"false_northing": 0.0
,"datum": "wgs84"}},"note": "this is going to be sweet"}' https://espa.cr.usgs.g
ov/api/v1/order
curl: option -96.0,latitude_of_origin:: is unknown
curl: try 'curl --help' or 'curl --manual' for more information

What is wrong with the latitude_of_origin parameter?

If I just make a very small change (like changing the sign of -96 to 96, other errors appear:

>C:\Users\User\Documents\curl-7.51.0\src\curl --user athanasis:XXXXX -XPOST -H 'Content-Type:application/json' -H 'Accept: application/json' -d '{"olitirs8": {"inputs": ["LC80270292015233LGN00"],
"products": ["sr"]},"format": "gtiff","resize": {"pixel_size": 60,"pixel_size_un
its": "meters"},"resampling_method": "nn","plot_statistics": true,"projection":
{"aea": {"standard_parallel_1": 29.5,"standard_parallel_2": 45.5,"central_meridi
an": 96.0,"latitude_of_origin": 23.0,"false_easting": 0.0,"false_northing": 0.0,
"datum": "wgs84"}},"note": "this is going to be sweet"}' https://espa.cr.usgs.go
v/api/v1/order
curl: (6) Couldn't resolve host 'application'
curl: (3) [globbing] unmatched brace in column 1
curl: (3) [globbing] bad range in column 2
curl: (3) [globbing] bad range in column 2
curl: (6) Couldn't resolve host 'gtiff,resize'
curl: (3) [globbing] unmatched brace in column 1
curl: (6) Couldn't resolve host '60,pixel_size_units'
curl: (3) [globbing] unmatched close brace/bracket in column 7
curl: (6) Couldn't resolve host 'nn,plot_statistics'
curl: (6) Couldn't resolve host 'true,projection'
curl: (3) [globbing] unmatched brace in column 1
curl: (3) [globbing] unmatched brace in column 1
curl: (6) Couldn't resolve host '29.5,standard_parallel_2'
curl: (6) Couldn't resolve host '45.5,central_meridian'
curl: (6) Couldn't resolve host '96.0,latitude_of_origin'
curl: (6) Couldn't resolve host '23.0,false_easting'
curl: (6) Couldn't resolve host '0.0,false_northing'
curl: (6) Couldn't resolve host '0.0,datum'
curl: (3) [globbing] unmatched close brace/bracket in column 6
curl: (3) [globbing] unmatched close brace/bracket in column 26
{
  "msg": "Could not parse the request into json",
  "status": 400
}


Any suggestions, please?
Thank you.

**Comment by caustin-usgs** [comment]
its a json formatting issue coming from windows, the syntax is different than the examples we have done from a *nix system, see the last comment on SO here: http://stackoverflow.com/questions/29576655/400-bad-request-when-post-json-in-flask

from cmd.exe

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\>curl --user username:xxxxx -d "{\"olitirs8\":{\"inputs\":[\"LC80270292015233LGN00\"], \"products\":[\"sr\"]},\"format\":\"gtiff\"}" https://espa.cr.usgs.gov/api/v1/order
{
  "orderid": "clay.austin.ctr@usgs.gov-11282016-200114-836",
  "status": 200
}

**Comment by caustin-usgs** [comment]
the backslashes didn't copy over in that last comment. basically the json needs to be wrapped in double quotes, and any key or value of type string needs to be wrapped in double quotes as well, but escaped with a \

**Comment by athanasis** [comment]
That was it!
Thank you very much!
