### ISSUE TITLE
Check to see if productid actually exists?

### ISSUE THREAD

**Issue by jgrn307** [USGS-EROS/espa-api#50]
Hi there -- great job getting the API working -- I'm working on an R wrapper for it, and some value-added functionality, but one thing I was trying to figure out is how to test if a product ACTUALLY exists in the archive.  I fed the API a set of properly formatted Landsat scenes, but with consecutive dates, only some of which could actually exist-- e.g. two weeks worth of dates, only one or two images should have been collected in that window.  All returned product info.  Is this only possible to check during the order phase?  Is there another way to go about this?  Cheers!

On a related note: is there a way to do a wild-card search for the GSI field?  Or are all GSIs within EROS for a given product the same?

**Comment by jakebrinkmann** [comment]
Hi there, thank you for your feedback. Some similar issues were encountered in #43 and our resolution will be to update our documentation for clarity. Ultimately, the espa-api tool intentionally expects users to already have a valid Level-1 scene id. Validation of whether products exist in the EROS archive is handled by the EROS inventory service. 

Some suggested resources to find these scene ids are:
1. Use the official [USGS/EROS Inventory Service API](https://earthexplorer.usgs.gov/inventory/documentation) which supports JSON/SOAP requests. 
1. All the metadata is updated daily and continuously [provided as a single (compressed) download](https://landsat.usgs.gov/download-entire-collection-metadata)

A temporary (unsupported) approach would be to prune your list by submitting an order to espa-api for processing, as the API will bounce your order and tell you which scenes were invalid:

```bash
$ curl -s --user $ESPAUSER:$ESPAPASS -d '{"inputs": ["LC80270292015233LGN00","LC80270292015234LGN00"]}' https://espa.cr.usg.gov/api/v1/available-products
{"olitirs8": {"inputs": ["LC80270292015233LGN00", "LC80270292015234LGN00"], "products": ["source_metadata", "l1", "toa", "bt", "cloud", "sr", "sr_ndvi", "sr_evi", "sr_savi", "sr_msavi", "sr_ndmi", "sr_nbr", "sr_nbr2", "stats", "swe"]}}

$ curl -s --user $ESPAUSER:$ESPAPASS -d '{"olitirs8": {"inputs": ["LC80270292015233LGN00","LC80270292015234LGN00"], "products": ["l1", "sr"]}, "format": "gtiff"}' https://espa.cr.usgs.gov/api/v1/order
{"message": {"Inputs Not Available": ["LC80270292015234LGN00"]},"status": 400}
```

**Comment by jgrn307** [comment]
Thanks!  I am working with that API (thanks for the direction), but for generating the API key, I can't figure out what part is the "url" and what part is the "POST" body.  If you were translating the API login generation into a simple CURL command, what would it be?

**Comment by jakebrinkmann** [comment]
Try this: 

```bash
$ curl  -d 'jsonRequest={"username":"$ESPAUSER","password":"$ESPAPASS"}' https://earthexplorer.usgs.gov/inventory/json/login
{"errorCode":null,"error":"","data":"<hash>","api_version":"1.2.1","executionTime":1.1997270584106}
```

This was generated using some help from the [sample query generation](https://earthexplorer.usgs.gov/inventory/documentation/test) page.

**Comment by jakebrinkmann** [comment]
The following bash code is then the solution to search for valid scene ids:

```bash
##### Login to get an APIKEY [https://earthexplorer.usgs.gov/inventory/documentation/json-api#login]
$ curl  -d 'jsonRequest={"username":"$ESPAUSER","password":"$ESPAPASS"}' https://earthexplorer.usgs.gov/inventory/json/login
{...,"data":"<hash>",...}

##### rawurlencode from http://stackoverflow.com/a/10660730/1533001
$ rawurldecode() {   printf -v REPLY '%b' "${1//%/\\x}" ;    echo "${REPLY}" ; }

##### Search [https://earthexplorer.usgs.gov/inventory/documentation/json-api#search]
$ args='{"datasetName":"LANDSAT_8","startDate":"2016-12-30","endDate":"2016-12-31","apiKey":"<hash>","node":"EE"}'
$ curl -s https:///earthexplorer.usgs.gov/inventory/json/search?jsonRequest=$(rawurlencode "$args")
{...,"data":{...,"results":[{...,"displayId":"LC80020282016365LGN00",...}],...}
```

I am not an expert on their services, [custserv@usgs.gov](mailto:custserv@usgs.gov) might be able to direct you to a better (more elegant) solution.
