### ISSUE TITLE
Mapping between inventory API product names and ordering API product names

### ISSUE THREAD

**Issue by jgrn307** [USGS-EROS/espa-api#57]
Hi there!  I'm working on an R wrapper for e.g. Earth Explorer using both the ESPA inventory and ordering API but I'm running into an issue:

When choosing datasets via the inventory system, it appears to be using satellite/sensor/product IDs from:

https://mapbox.github.io/usgs/reference/catalog/hdds.html

E.G. for Landsat 8 Surface Reflectance I would use "LSR_LANDSAT_8" for the inventory API to search for datasets.

However, if I want to then move this to an ordering context, it appears I need to map this to something like:

"{\"olitirs8\": {\"inputs\": [\"LC80270292015233LGN00\"],\"products\": [\"sr\"]},\"format\": \"gtiff\"}"

Is there some lookup table that I can use to map e.g. "LSR_LANDSAT_8" (the search product ID) to "olitirs8", "sr" (the ordering ID)?  Right now, all I can figure is I have to hand-code this entire lookup table.  Cheers!

**Comment by caustin-usgs** [comment]
hello @jgrn307 you can use the available-products [endpoint](https://github.com/USGS-EROS/espa-api#apiProdsGet) in the api to return the properly formatted json

**Comment by jgrn307** [comment]
caustin-- thanks, but I was asking about the link between:

https://earthexplorer.usgs.gov/inventory/documentation/json-api#search

and the ordering API.  Maybe I'm misunderstanding something, but the "datasetName" in the inventory API  seems to be an odd mix of satellite/sensor/product -- would e.g. LSR_LANDSAT_8 imply "oli8" and "sr"?  

I actually like how you guys are doing the arrangement better than the long list of somewhat inconsistently named https://mapbox.github.io/usgs/reference/catalog/hdds.html that the inventory API uses, but if I wanted to write a script that, says, searches for and orders L8 surface reflectance, it seems they'd need to know both the inventory datasetName, the ordering sensor name, and the ordering product name, that latter two seem to be somewhat redundant to the datasetName (or vice versa -- the sensor/product seems like they could be mapped to an inventory datasetName).

**Comment by caustin-usgs** [comment]
the earthexplorer json-api is a completely separate tool from the ESPA api

**Comment by jgrn307** [comment]
I understand that -- but it seems like the links between the searching API and the ordering API should be tightly linked (since you need the search results to order the products, no?  is there a different ESPA search API I'm missing?)  Having a mapped database of search datasetnames and order sensor/product names would probably be sufficient.

To be clear: I'm trying to make a fully command-line search/order tool for the R environment.  I've got all the earthexplorer and ESPA api's wrapped at this point (I'm happy to share the "beta" with anyone who is interested), but I'm working on trying to come up with some value-added tools that allow you to bother search and order using the same command line interface.

Cheers!

**Comment by jakebrinkmann** [comment]
@jgrn307 you don't need to know the dataset name for the API. As @caustin-usgs pointed out, after doing your search to the inventory API, take the scene names, and make a request to `https://espa.cr.usgs.gov/api/v0/available-products`

```bash
$ curl --data-urlencode 'jsonRequest={"datasetName":"LANDSAT_8","startDate":"2016-12-30","endDate":"2016-12-31","apiKey":"<hash>","node":"EE"}'  https:///earthexplorer.usgs.gov/inventory/json/search
{...,"data":{...,"results":[{...,"displayId":"LC80020282016365LGN00",...}],...}

$ curl --user $ESPAUSER:$ESPAPASS https://espa.cr.usgs.gov/api/v0/available-products/LC80020282016365LGN00
{"olitirs8": {"inputs": ["LC80020282016365LGN00"], "products": ["source_metadata", "l1", "toa", "bt", "cloud", "sr", "sr_ndvi", "sr_evi", "sr_savi", "sr_msavi", "sr_ndmi", "sr_nbr", "sr_nbr2", "stats", "swe"]}}
```

**Comment by jgrn307** [comment]
Gotcha, and I'm working on that right now (using the entity IDs to pass to the ordering system) -- but it is mostly mapping the "LANDSAT_8" to "olitirs8" that I'm talking about.  I can create this lookup table, but it seems like this is a dynamic database that could be kept on your end?

**Comment by jgrn307** [comment]
(also, it looks like TM4 and TM5 are mixed up together in the search API as "LANDSAT_TM" so I'd have to parse the entity IDs I guess to figure out which one it is?)

**Comment by jakebrinkmann** [comment]
> If there was a way to send ONLY the scene IDs that would be great

Try this:
```bash
$ curl --user username:password https://espa.cr.usgs.gov/api/v0/available-products/LC80020282016365LGN00
```

**Comment by jakebrinkmann** [comment]
A complete bash example will require knowing the initial desired `LANDSAT_8` dataset comes from `EE` node:

```bash
ESPAUSER=<insertyourusername>
ESPAPASS=<insertyourpassword>
node="EE"
sensor="LANDSAT_8"
startdate=$(date -d "10 days ago" "+%Y-%m-%d")
enddate=$(date -d "5 days ago" "+%Y-%m-%d")

args="jsonRequest={\"username\":\"$ESPAUSER\",\"password\":\"$ESPAPASS\"}"
hash=$(curl -s -d "$args" https://earthexplorer.usgs.gov/inventory/json/login | sed -e "s/^.*\"data\":\"\(\w*\)\".*$/\1/")

args="jsonRequest={\"datasetName\":\"$sensor\",\"startDate\":\"$startdate\",\"endDate\":\"$enddate\",\"apiKey\":\"$hash\",\"node\":\"$node\"}"
sceneid=$(curl --data-urlencode "$args" https://earthexplorer.usgs.gov/inventory/json/search | sed -e "s/^.*\"entityId\":\"\(\w*\)\".*$/\1/")

orderinfo=$(curl --user $ESPAUSER:$ESPAPASS https://espa.cr.usgs.gov/api/v0/available-products/$sceneid | sed -e "s/\"products\":\s\[\(.*\)\]/\"products\": \[\"sr\"\]/")
orderinfo=$(echo "$orderinfo" | sed -e "s/\}\}/}, \"format\": \"gtiff\"}/")
curl --user $ESPAUSER:$ESPAPASS -d "$orderinfo" https://espa.cr.usgs.gov/api/v0/order

```

You will find no additional look-up-table for the espa-api is required, as the `available-products` endpoint formatted the order for you

**Comment by jgrn307** [comment]
Awesome!  Got it!  Working great now.  Do you guys keep track of "wrappers" as they are created?  I'm happy to send you the link to the R wrapper once it clears CRAN.

**Comment by jakebrinkmann** [comment]
We always appreciate knowing how users are interacting with the services. If you leave a link to your code/license/documentation, we would consider ways of incorporating a shout-out to it into our documentation. Thanks!
