### ISSUE TITLE
Number of concurrent downloads allowed?

### ISSUE THREAD

**Issue by jgrn307** [USGS-EROS/espa-api#59]
This is KINDOF related to the API, but when using download URLs, is there a max number of concurrent downloads that are allowed by the system, if I wanted to enable parallel downloads?

**Comment by jakebrinkmann** [comment]
Yes, the services will start returning 503 responses for frequent/concurrent requests. It looks like having up to **5 open connections** making up to **2 requests per second** should be ok.

A python project you could maybe pull some inspiration from: [espa-bulk-downloader](https://github.com/USGS-EROS/espa-bulk-downloader)
