### ISSUE TITLE
"Authorized" ordering?

### ISSUE THREAD

**Issue by jgrn307** [USGS-EROS/espa-api#61]
Hi there -- the beta of my R wrappers for the ESPA search/ordering are ready to be tested (install.packages("espa.tools", repos="http://R-Forge.R-project.org")), but a colleague of mine was asking how he would go about ordering "authorized" products (he is at DOE and has access to e.g. the Worldview products) -- do you know if the ESPA search and order APIs will work with these authorized packages?  I don't have access to any of them, so I can't test it out.  Cheers!

**Comment by jakebrinkmann** [comment]
Thanks @jgrn307 for linking your R package! Glad it is working for you. 

ESPA science algorithms currently focus on generating Landsat products: 
* [Landsat Surface Reflectance Higher-Level Data Products](https://landsat.usgs.gov/landsat-surface-reflectance-high-level-data-products) 
* [Landsat Higher-Level Data Products](https://landsat.usgs.gov/cdr-ecv)
