### ISSUE TITLE
data types and formats

### ISSUE THREAD

**Issue by samdoolin** [USGS-EROS/espa-api#80]
I have been writing some code against the USGS EROS JSON API and come across what I believe to be a number of minor data type and format inconsistencies within the API which I would like to bring to your attention.

The issues bellow could well be planned changes for an upcoming API version, or small details which may have been overlooked. I would greatly appreciate a heads-up if these may be changed in the future.

The following are the inconsistencies which I uncovered whilst validating API responses against json-schema:

API Method | Field in response | Issue
--- | --- | ---
Dataset Search | data.orderLimit | string not number
Dataset Fields | data.fieldId | string not number
Scene Search Hits | data (i.e. number of hits) | string not number
Scene Search | data.results..startTime | date not time
Scene Search | data.results..endTime | date not time
Scene Metadata | data..startTime | date not time
Scene Metadata | data..endTime | date not time
Status | data.build_date | Format appears to be YYYY-DD-MM, whilst other dates returned are YYYY-MM-DD

Best wishes

**Comment by jakebrinkmann** [comment]
Hi there!
Thank you for the very detailed report! Apologies if I am mistaken, but you appear to be referencing the [EarthExplorer JSON API](https://earthexplorer.usgs.gov/inventory/documentation/json-api), not the [**ESPA** API](https://espa.cr.usgs.gov). 
If that is correct, please use the [Landsat Contact Us](https://landsat.usgs.gov/contactus.php) page and specify EarthExplorer JSON API in the "Subject" section.

**Comment by samdoolin** [comment]
Thanks for the quick response. You are correct. I was directed here by custserv@usgs.gov.
