### ISSUE TITLE
Download Landsat8 with LonLat projection 

### ISSUE THREAD

**Issue by hamidsalehi2007** [USGS-EROS/espa-api#81]
`python -2.7`:  
`ubuntu 16.04`:  

Dear colleague
I am using the new API of your site to retrieve data.
https://github.com/USGS-EROS/espa-api

I have a problem for ordering Landsat8 data by projection lonlat (Geographic) and I use this format for it. 

```
projection =  { "lonlat": {
                                    "type": "null"
                                    }
                    }

```
But, when I run it I get error. The error is :

```{
    "status": 400, 
    "message": {
        "1 validation errors:": [
            "Value {u'type': u'null'} for field 'projection.lonlat' is not of type null"
        ]
    }
}
```

When I use 'aea' format, it works correctly, but I need data in lonlat format.
How to fix this error?

Best wishes

**Comment by jakebrinkmann** [comment]
Hi there, `null` is the JSON type (like numbers or strings) that projection looks for. Try this: 
```json
    "projection":{
        "lonlat":null
    },
```

**Comment by pd-Shah** [comment]
Hello all

@jakebrinkmann: python doesn't know null type.
```
error:
Traceback (most recent call last):
    "lonlat":null
NameError: name 'null' is not defined
```

**Comment by pd-Shah** [comment]
python doesn't have null type.
in python set it to None type:
```
>>> json_style='''
{"lonlat":null}
'''
>>> python_style=json.loads(json_style)
>>> python_style
{u'lonlat': **None**}
>>> json_style=json.dumps(python_style)
>>> json_style
'{"lonlat": **null**}'
>>> 
```
