### ISSUE TITLE
server URL not found

### ISSUE THREAD

**Issue by bucricket** [USGS-EROS/espa-api#82]
# BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

* `curl -V` or `python -V`:  
* `uname -a`:  

List the steps to reproduce the issue:

1. curl --user user:pass https://espa.cr.usgs.gov/api/v0/list-order

Describe the results you received:
{"status": 404, "message": "The requested URL was not found on the server."}

Describe the results you expected:
I was expecting to see the results that reflect the orders I have on the online ESPA bulk order interface.

Provide additional info you think is important:

# ----- END REPORT -----

**Comment by jakebrinkmann** [comment]
Hi! Thanks for using the report template. Still a work in progress. Try adding an `s` to the end of the url. 
```
GET /api/v0/list-orders
```

More docs [here](https://github.com/USGS-EROS/espa-api/blob/master/docs/API-RESOURCES-LIST.md#apiOrders).

**Comment by bucricket** [comment]
Did that command change in the last few days?  

Mitch
