### ISSUE TITLE
Landsat Collect 1 issues?

### ISSUE THREAD

**Issue by jgrn307** [USGS-EROS/espa-api#86]
Hi there -- it looks like something weird happened when the Landsat Collect 1 stuff was released in terms of the naming/lookup.  When I use the EarthExplorer API to do a search for/retrieval of names for LANDSAT_8_C1 products ("LANDSAT_8" no longer exists it seems), I get an entityId of e.g. "LC81422132016258LGN01".  When I then pipe this into available-products, I no longer get a "sr" product available.  Any ideas what might be going on?

**Comment by jakebrinkmann** [comment]
Hi, yes, the ESPA system accepts the IDs using the Collection-01 formatting convention. I believe the EarthExplorer API lists that format as the "displayId" (instead of "entityId")

Example: 
```bash
curl -n https://espa.cr.usgs.gov/api/v1/available-products \
  -X GET -d '{"inputs": ["LC08_L1TP_156063_20170207_20170216_01_T1"]}'
```

**Comment by jgrn307** [comment]
Gotcha -- are the Landsat C1 products the only ones that switched to using the displayID?  I was able to get this working, but I wanted to make sure other products would work correctly...

**Comment by jakebrinkmann** [comment]
Yes, the espa-api currently handles Landsat 8, ETM, and TM largely the same. 

If using Landsat, interacting with e.g. the LANDSAT_8_C1 dataset on EarthExplorer, the entityId/displayId maps to the Scene-ID/Product-ID respectively. 

For more information on the Product-ID, check out the [description for Landsat Collections](https://landsat.usgs.gov/landsat-collections)
