### ISSUE TITLE
Search using latlong or tileId?

### ISSUE THREAD

**Issue by luizpizano** [USGS-EROS/espa-api#95]
Dear all,
How can I search all valid scenes Id using a tileId and a period? The only possibility I've found in the Api is to provide a productId to receive its available products.
Thank you in advance.

**Comment by jakebrinkmann** [comment]
Hello there, 
Take a look over at #93 to see if the discussion around a similar problem helps. ESPA's mission is on-demand creation of science products from supported input types, so the available products are what algorithms ESPA can execute on a given input set. 

Currently the most supported way of searching the EROS inventory for inputs into ESPA is via the [EROS Inventory Service (Machine-to-Machine)](https://earthexplorer.usgs.gov/inventory/documentation)

**Comment by luizpizano** [comment]
@jakebrinkmann , the api solved the problem, thank you. The only problem I found there was that the response of a search always had a maximum of 10 scenes per tile, so I had to break large periods in periods of 4 months to do the search.

**Comment by jakebrinkmann** [comment]
Good to hear. It looks like [the search endpoint](https://earthexplorer.usgs.gov/inventory/documentation/json-api#search) takes a `"maxResults"` parameter, which defaults to 10
