### ISSUE TITLE
/available-products returns date_restricted field

### ISSUE THREAD

**Issue by luizpizano** [USGS-EROS/espa-api#98]
"date_restricted": {
        "sr_ndmi": [
            "LC08_L1TP_223074_20160226_20170329_01_T1"
        ], 
was part of the return for the /available-products API. What does that field mean?

**Comment by jakebrinkmann** [comment]
There are some dates where the auxiliary inputs required for calculating Surface Reflectance are not available. See [Caveats and Constraints here](https://landsat.usgs.gov/landsat-surface-reflectance-high-level-data-products)

**Comment by luizpizano** [comment]
@jakebrinkmann , thank you. That means date_restricted products are not available then.

**Comment by ThatAdamsGuy** [comment]
Just a heads up for anybody stumbling on this in the future, the [Caveats and Constraints](https://www.usgs.gov/land-resources/nli/landsat/landsat-surface-reflectance?qt-science_support_page_related_con=0#qt-science_support_page_related_con) article that @jakebrinkmann linked has moved and is available in the link above.
